# Casdoor program config (Beego INI). GENERATED by cli.sh into
# data/<instance>_config/app.conf and re-rendered on every `start`.
# Do NOT edit the generated file by hand; change settings_casdoor.conf instead.

# --- Web server ---
appname = casdoor
# in-container port; host port is mapped via -p (CASDOOR_PORT)
httpport = 8000
runmode = prod
sessionon = true
copyrequestbody = true

# --- Database ---
# Placeholders below are filled by cli.sh from settings_casdoor.conf (external mode)
# or settings_paradedb.conf (bundled mode).
driverName = postgres
# Connects to the bootstrap DB (usually 'postgres'); Casdoor then creates dbName on it.
dataSourceName = user={{CASDOOR_DB_USER}} password={{CASDOOR_DB_PASSWORD}} host={{CASDOOR_DB_HOST}} port={{CASDOOR_DB_PORT}} sslmode=disable dbname={{CASDOOR_DB_BOOTSTRAP}}
# Application DB Casdoor actually uses; auto-created and migrated on first start.
dbName = {{CASDOOR_DB_NAME}}

# --- Misc ---
enableGzip = true
sessionTimeout = 3600
