# Sub2API Settings

# === Sub2API ===
INSTANCE_NAME="{{INSTANCE_NAME}}"
SUB2API_PORT="{{SUB2API_PORT}}"
TZ="Asia/Shanghai"

# Server runtime
SERVER_MODE="release"
RUN_MODE="standard"

# === Admin account (auto-created on first run) ===
ADMIN_EMAIL="admin@sub2api.local"
ADMIN_PASSWORD="{{ADMIN_PASSWORD}}"

# === JWT ===
# NEVER change after first start: existing login sessions would be invalidated.
JWT_SECRET="{{JWT_SECRET}}"
JWT_EXPIRE_HOUR="24"

# === TOTP (2FA) ===
# NEVER change after first start: existing 2FA secrets cannot be decrypted.
TOTP_ENCRYPTION_KEY="{{TOTP_ENCRYPTION_KEY}}"

# === Database connection pool ===
DATABASE_MAX_OPEN_CONNS="50"
DATABASE_MAX_IDLE_CONNS="10"
DATABASE_CONN_MAX_LIFETIME_MINUTES="30"
DATABASE_CONN_MAX_IDLE_TIME_MINUTES="5"

# === Redis ===
# Bundled redis runs without a password inside the private network.
REDIS_PASSWORD=""
REDIS_DB="0"
REDIS_POOL_SIZE="1024"
REDIS_MIN_IDLE_CONNS="10"
REDIS_ENABLE_TLS="false"

# === Gemini OAuth (optional, for Gemini accounts) ===
GEMINI_OAUTH_CLIENT_ID=""
GEMINI_OAUTH_CLIENT_SECRET=""
GEMINI_OAUTH_SCOPES=""
GEMINI_QUOTA_POLICY=""
GEMINI_CLI_OAUTH_CLIENT_SECRET=""
ANTIGRAVITY_OAUTH_CLIENT_SECRET=""
ANTIGRAVITY_USER_AGENT_VERSION=""

# === Security: URL allowlist ===
SECURITY_URL_ALLOWLIST_ENABLED="false"
SECURITY_URL_ALLOWLIST_ALLOW_INSECURE_HTTP="false"
SECURITY_URL_ALLOWLIST_ALLOW_PRIVATE_HOSTS="false"
SECURITY_URL_ALLOWLIST_UPSTREAM_HOSTS=""

# === Online updates ===
# Proxy for accessing GitHub (online updates + pricing data).
# Examples: http://host:port, socks5://host:port
UPDATE_PROXY_URL=""

# === Gateway: image stream & concurrency ===
GATEWAY_OPENAI_RESPONSE_HEADER_TIMEOUT="0"
GATEWAY_OPENAI_HTTP2_ENABLED="true"
GATEWAY_OPENAI_HTTP2_ALLOW_PROXY_FALLBACK_TO_HTTP1="true"
GATEWAY_OPENAI_HTTP2_FALLBACK_ERROR_THRESHOLD="2"
GATEWAY_OPENAI_HTTP2_FALLBACK_WINDOW_SECONDS="60"
GATEWAY_OPENAI_HTTP2_FALLBACK_TTL_SECONDS="600"
GATEWAY_IMAGE_STREAM_DATA_INTERVAL_TIMEOUT="900"
GATEWAY_IMAGE_STREAM_KEEPALIVE_INTERVAL="10"
GATEWAY_IMAGE_CONCURRENCY_ENABLED="false"
GATEWAY_IMAGE_CONCURRENCY_MAX_CONCURRENT_REQUESTS="0"
GATEWAY_IMAGE_CONCURRENCY_OVERFLOW_MODE="reject"
GATEWAY_IMAGE_CONCURRENCY_WAIT_TIMEOUT_SECONDS="30"
GATEWAY_IMAGE_CONCURRENCY_MAX_WAITING_REQUESTS="100"
