# RustFS Settings (Lightweight S3)
INSTANCE_NAME="{{INSTANCE_NAME}}"

# Host Ports
RUSTFS_PORT="{{RUSTFS_PORT}}"
RUSTFS_ADMIN_PORT="{{RUSTFS_ADMIN_PORT}}"

# API Keys
RUSTFS_ACCESS_KEY="{{RUSTFS_ACCESS_KEY}}"
RUSTFS_SECRET_KEY="{{RUSTFS_SECRET_KEY}}"
