#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# 1. Initialization & Path Anchoring
# -----------------------------------------------------------------------------
COMMAND=${1:-help}
shift || true

CONF_FILE=""
NAME_OVERRIDE=""
EXTRA_ARGS=()
while [ $# -gt 0 ]; do
    case "$1" in
        --conf) CONF_FILE="$2"; shift 2 ;;
        --name) NAME_OVERRIDE="$2"; shift 2 ;;
        *) EXTRA_ARGS+=("$1"); shift ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TPL_DIR="$SCRIPT_DIR/templates"
CONF_FILE="${CONF_FILE:-$SCRIPT_DIR/settings_librechat.conf}"
CONF_DIR="$(cd "$(dirname "$CONF_FILE")" && pwd)"
HOOK_RUN_ARGS=()

[ -f "$SCRIPT_DIR/hooks.sh" ] && source "$SCRIPT_DIR/hooks.sh"
hook() { if declare -F "$1" >/dev/null; then "$1"; fi; }

# -----------------------------------------------------------------------------
# 2. Utility Functions
# -----------------------------------------------------------------------------
hr() { echo "-----------------------------------------------------------------------------"; }
random_secret() { openssl rand -hex 32; }
random_iv() { openssl rand -hex 16; }

require_conf() {
    if [ ! -f "$CONF_FILE" ]; then
        echo "[ERROR] [LibreChat] $CONF_FILE not found. Run 'bash cli.sh init' first."
        exit 1
    fi
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "[ERROR] [LibreChat] Required command not found: $1"
        exit 1
    fi
}

repo_dir() { printf '%s/data/%s_src/LibreChat' "$CONF_DIR" "$INSTANCE_NAME"; }

compose_cmd() {
    if docker compose version >/dev/null 2>&1; then
        docker compose "$@"
    elif command -v docker-compose >/dev/null 2>&1; then
        docker-compose "$@"
    else
        echo "[ERROR] [LibreChat] Docker Compose is required."
        exit 1
    fi
}

# -----------------------------------------------------------------------------
# 3. Service Config Rendering
# -----------------------------------------------------------------------------
generate_settings() {
    local name="$NAME_OVERRIDE"
    if [ -z "$name" ]; then
        local ts=$(date +%s)
        name="librechat_${ts: -4}"
    fi

    sed -e "s/{{INSTANCE_NAME}}/${name}/g" \
        -e "s/{{JWT_SECRET}}/$(random_secret)/g" \
        -e "s/{{JWT_REFRESH_SECRET}}/$(random_secret)/g" \
        -e "s/{{CREDS_KEY}}/$(random_secret)/g" \
        -e "s/{{CREDS_IV}}/$(random_iv)/g" \
        -e "s/{{MEILI_MASTER_KEY}}/$(random_secret)/g" \
        -e "s/{{ADMIN_PANEL_SESSION_SECRET}}/$(random_secret)/g" \
        "$TPL_DIR/settings_librechat.conf.tpl" > "$CONF_FILE"
}

clone_repo() {
    local target_dir
    target_dir="$(repo_dir)"

    if [ -d "$target_dir/.git" ]; then
        echo "[INFO] LibreChat source already exists: $target_dir"
        return
    fi

    require_command git
    mkdir -p "$(dirname "$target_dir")"
    git clone "$LIBRECHAT_REPO_URL" "$target_dir"
}

render_env_file() {
    local target_dir env_file
    target_dir="$(repo_dir)"
    env_file="$target_dir/.env"

    printf '%s\n' \
        '# Generated by script_tools deploy_apps/librechat.' \
        "# Edit settings_librechat.conf, then run 'bash cli.sh init' to sync this file." \
        '' \
        'HOST=0.0.0.0' \
        "PORT=${LIBRECHAT_PORT}" \
        'NODE_ENV=production' \
        '' \
        "DOMAIN_CLIENT=${DOMAIN_CLIENT}" \
        "DOMAIN_SERVER=${DOMAIN_SERVER}" \
        "ADMIN_PANEL_URL=${ADMIN_PANEL_URL}" \
        "ADMIN_PANEL_SESSION_SECRET=${ADMIN_PANEL_SESSION_SECRET}" \
        "ADMIN_PANEL_SESSION_COOKIE_SECURE=${ADMIN_PANEL_SESSION_COOKIE_SECURE}" \
        '' \
        'NO_INDEX=true' \
        'TRUST_PROXY=1' \
        'CONSOLE_JSON=false' \
        'DEBUG_LOGGING=false' \
        'DEBUG_CONSOLE=false' \
        'LOG_TO_FILE=true' \
        '' \
        "JWT_SECRET=${JWT_SECRET}" \
        "JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}" \
        "CREDS_KEY=${CREDS_KEY}" \
        "CREDS_IV=${CREDS_IV}" \
        '' \
        "ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN}" \
        "ALLOW_REGISTRATION=${ALLOW_REGISTRATION}" \
        'ALLOW_SOCIAL_LOGIN=false' \
        'ALLOW_SOCIAL_REGISTRATION=false' \
        'ALLOW_PASSWORD_RESET=false' \
        "ALLOW_UNVERIFIED_EMAIL_LOGIN=${ALLOW_UNVERIFIED_EMAIL_LOGIN}" \
        '' \
        'MONGO_URI=mongodb://mongodb:27017/LibreChat' \
        "SEARCH=${SEARCH}" \
        'MEILI_NO_ANALYTICS=true' \
        'MEILI_HOST=http://meilisearch:7700' \
        "MEILI_MASTER_KEY=${MEILI_MASTER_KEY}" \
        '' \
        "RAG_PORT=${RAG_PORT}" \
        "RAG_API_URL=http://rag_api:${RAG_PORT}" \
        "EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER}" \
        "EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}" \
        '' \
        "OPENAI_API_KEY=${OPENAI_API_KEY}" \
        "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" \
        "GOOGLE_KEY=${GOOGLE_KEY}" \
        "OPENROUTER_KEY=${OPENROUTER_KEY}" \
        "DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}" \
        "GROQ_API_KEY=${GROQ_API_KEY}" \
        "MISTRAL_API_KEY=${MISTRAL_API_KEY}" \
        "PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}" \
        "TOGETHERAI_API_KEY=${TOGETHERAI_API_KEY}" \
        '' \
        "PROXY=${PROXY}" \
        "HTTP_PROXY=${HTTP_PROXY}" \
        "HTTPS_PROXY=${HTTPS_PROXY}" \
        "NO_PROXY=${NO_PROXY}" \
        "http_proxy=${http_proxy}" \
        "https_proxy=${https_proxy}" \
        "no_proxy=${no_proxy}" \
        '' \
        "APP_TITLE=${APP_TITLE}" \
        "HELP_AND_FAQ_URL=${HELP_AND_FAQ_URL}" \
        > "$env_file"
}

# -----------------------------------------------------------------------------
# 4. Lifecycle Functions (do_xxx)
# -----------------------------------------------------------------------------
do_init() {
    hr
    echo "[INFO] [LibreChat] Initializing configuration and official source..."
    hr

    [ ! -f "$CONF_FILE" ] && generate_settings
    source "$CONF_FILE"
    hook on_init

    clone_repo
    render_env_file

    hr
    echo "[SUCCESS] LibreChat initialization completed!"
    hr
    echo "[IMPORTANT] Recommended next steps:"
    echo "  1. Review settings_librechat.conf"
    echo "  2. Run 'bash cli.sh start' to bring up LibreChat via official docker compose"
    echo "  3. Register the first account in the browser; it becomes the admin account"
    echo "Source directory: $(repo_dir)"
    echo "Access URL: ${DOMAIN_CLIENT}"
    hr
}

do_start() {
    require_conf
    set -a; source "$CONF_FILE"; set +a
    hook on_start

    local target_dir
    target_dir="$(repo_dir)"
    if [ ! -d "$target_dir/.git" ]; then
        echo "[ERROR] [LibreChat] Source directory not found. Run 'bash cli.sh init' first."
        exit 1
    fi

    render_env_file

    hr
    echo "[INFO] Starting LibreChat via official docker compose..."
    hr
    (cd "$target_dir" && compose_cmd up -d)
    hr
    echo "[SUCCESS] LibreChat is up and running!"
    echo "Access URL: ${DOMAIN_CLIENT}"
    hr
}

do_stop() {
    require_conf
    source "$CONF_FILE"
    local target_dir
    target_dir="$(repo_dir)"

    hr
    echo "[INFO] Stopping LibreChat..."
    hr
    if [ -d "$target_dir" ]; then
        (cd "$target_dir" && compose_cmd down)
    fi
    hook on_stop
}

do_rm() {
    require_conf
    source "$CONF_FILE"
    local target_dir
    target_dir="$(repo_dir)"

    hr
    echo "[INFO] Removing LibreChat containers..."
    hr
    if [ -d "$target_dir" ]; then
        (cd "$target_dir" && compose_cmd down)
    fi
    hook on_rm
}

do_purge() {
    require_conf
    source "$CONF_FILE"
    local target_dir data_dir
    target_dir="$(repo_dir)"
    data_dir="${CONF_DIR}/data/${INSTANCE_NAME}_src"

    hr
    echo "[WARN] WARNING: Preparing to completely destroy LibreChat data and source checkout!"
    hr
    if [ -d "$target_dir" ]; then
        (cd "$target_dir" && compose_cmd down -v)
    fi
    if [ -d "$data_dir" ]; then
        rm -rf "$data_dir"
    fi
    hook on_purge

    hr
    echo "[SUCCESS] LibreChat data has been purged (configs preserved)."
    hr
}

do_reset() {
    do_purge
    echo "[INFO] Removing all generated settings under this service..."
    rm -f "$CONF_DIR"/settings*.conf
    hr
    echo "[SUCCESS] LibreChat reset complete (restored to pristine source files)."
    hr
}

do_help() {
    echo "Usage: $0 {init|start|up|stop|rm|purge|reset} [--conf PATH] [--name NAME]"
    echo "  init    : Generate settings_librechat.conf, clone LibreChat, and render .env"
    echo "  start   : Start LibreChat using the official docker compose files"
    echo "  up      : Initialize config/source and start LibreChat instantly"
    echo "  stop    : Stop running containers"
    echo "  rm      : Remove containers (preserves source checkout, data volumes, and settings)"
    echo "  purge   : DANGER - Remove containers, volumes, and local source checkout (preserves settings)"
    echo "  reset   : DANGER - purge AND delete ALL settings (back to pristine source files)"
    echo ""
    echo "Options:"
    echo "  --conf PATH : Config file location (default: <script_dir>/settings_librechat.conf)."
    echo "  --name NAME : Full instance name to write at init (default: auto 'librechat_<ts>')."
}

# -----------------------------------------------------------------------------
# 5. Command Dispatch
# -----------------------------------------------------------------------------
case "$COMMAND" in
    init)    do_init ;;
    start)   do_start ;;
    up)      do_init && do_start ;;
    stop)    do_stop ;;
    rm)      do_rm ;;
    purge)   do_purge ;;
    reset)   do_reset ;;
    network) if declare -F on_network >/dev/null; then require_conf; source "$CONF_FILE"; on_network "${EXTRA_ARGS[@]}"; else do_help; fi ;;
    *)       do_help ;;
esac
